name: My First Workflow

on: push

jobs:
    practice_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v4
        - name: welcome message
          run: |
            echo "My first GitHub Action Job"
            ls -ltra
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON" >> dragon.txt


